### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by csterritt** [nerdguru/go-sls-crud#1]
Hey -- thanks for doing this, it's really nice to have an example integrated with serverless.

But it won't compile, out of the box:

    $ make
    dep ensure
    env GOOS=linux go build -ldflags="-s -w" -o bin/get functions/get.go
    functions/get.go:6:2: cannot find package "go-sls-crudl/moviedao" in any of:
            /Volumes/Second/Chris/hacks/gofigure/src/github.com/csterritt/go-sls-crudl/vendor/go-sls-crudl/moviedao (vendor tree)
            /usr/local/Cellar/go/1.11.2/libexec/src/go-sls-crudl/moviedao (from $GOROOT)
            /Volumes/Second/Chris/hacks/gofigure/src/go-sls-crudl/moviedao (from $GOPATH)
    make: *** [build] Error 1

I've found that I have to change the `moviedao` import to:

    "github.com/nerdguru/go-sls-crudl/moviedao"

Then it will compile.  Of course, that means that there's another copy of the code under `vendor/github.com/nerdguru/go-sls-crudl`, so I'd have to edit its copy of `moviedao` if I wanted to change it.

I'm pretty much a go newbie myself, so I'll see if I can't figure it out.

**Comment by petecj2** [comment]
Thanks so much for pointing this out.  I admit that I haven't touched this in about 6 months and struggled with the packaging even when I was working with it regularly.  I'm hardly a Golang expert even now, so if you find what works for you I'd happily accept a PR on it.

**Comment by csterritt** [comment]
PR sent -- and I even got the Makefile only building dependencies, and compiling the go files, when necessary.
